"""empty message

Revision ID: 291ed5e9716b
Revises: 6f1dc96d75df
Create Date: 2023-05-01 16:39:26.280486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291ed5e9716b'
down_revision = '6f1dc96d75df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
